### ISSUE TITLE
爬虫结束后程序未停止

### ISSUE THREAD

**Issue by gonedead** [conlin-huang/aio-scrapy#1]
运行single_quotes.py:中代码，发现爬虫执行完所有任务后并未结束脚本，不知什么原因

**Comment by conlin-huang** [comment]
将`CLOSE_SPIDER_ON_IDLE`(爬虫空闲的时候是否关闭) 这个参数设置为True就行了，默认是False。

**Comment by gonedead** [comment]
十分感谢，不过documentation_zh.md中关于CLOSE_SPIDER_ON_IDLE的描述应该写错了。
> ```CLOSE_SPIDER_ON_IDLE``` : 当没有队列任务的时候是否关闭爬虫, 默认 True.

**Comment by conlin-huang** [comment]
确实是文档写错了，已修复。
